from prompts.types import SystemPrompts
from prompts.common import (
    IMPORTED_CODE_COMMON_BULLETS,
    IMPORTED_CODE_SVG_BULLETS,
    LIB_BOOTSTRAP_LINK,
    LIB_FONT_AWESOME,
    LIB_GOOGLE_FONTS,
    LIB_IONIC_IONICONS,
    LIB_IONIC_SCRIPTS,
    LIB_REACT_SCRIPTS,
    LIB_TAILWIND_SCRIPT,
    LIB_VUE_SCRIPT,
    VUE_GLOBAL_BUILD_EXAMPLE,
    FORMAT_HTML,
    FORMAT_HTML_ONLY_CODE,
    FORMAT_SVG,
)


IMPORTED_CODE_TAILWIND_SYSTEM_PROMPT = f"""
You are an expert Tailwind developer.

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_TAILWIND_SCRIPT}
{LIB_GOOGLE_FONTS}
{LIB_FONT_AWESOME}

{FORMAT_HTML}"""

IMPORTED_CODE_HTML_CSS_SYSTEM_PROMPT = f"""
You are an expert CSS developer.

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_GOOGLE_FONTS}
{LIB_FONT_AWESOME}

{FORMAT_HTML}"""

IMPORTED_CODE_REACT_TAILWIND_SYSTEM_PROMPT = f"""
You are an expert React/Tailwind developer

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_REACT_SCRIPTS}
- Use this script to include Tailwind: <script src="https://cdn.tailwindcss.com"></script>
{LIB_GOOGLE_FONTS}
{LIB_FONT_AWESOME}

{FORMAT_HTML}"""

IMPORTED_CODE_BOOTSTRAP_SYSTEM_PROMPT = f"""
You are an expert Bootstrap developer.

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_BOOTSTRAP_LINK}
{LIB_GOOGLE_FONTS}
{LIB_FONT_AWESOME}

{FORMAT_HTML}"""

IMPORTED_CODE_IONIC_TAILWIND_SYSTEM_PROMPT = f"""
You are an expert Ionic/Tailwind developer.

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_IONIC_SCRIPTS}
{LIB_TAILWIND_SCRIPT}
{LIB_GOOGLE_FONTS}
{LIB_IONIC_IONICONS}

{FORMAT_HTML}"""

IMPORTED_CODE_VUE_TAILWIND_SYSTEM_PROMPT = f"""
You are an expert Vue/Tailwind developer.

{IMPORTED_CODE_COMMON_BULLETS}

In terms of libraries,

{LIB_VUE_SCRIPT}
{VUE_GLOBAL_BUILD_EXAMPLE}
- Use this script to include Tailwind: <script src="https://cdn.tailwindcss.com"></script>
{LIB_GOOGLE_FONTS}
{LIB_FONT_AWESOME}

{FORMAT_HTML_ONLY_CODE}"""

IMPORTED_CODE_SVG_SYSTEM_PROMPT = f"""
You are an expert at building SVGs.

{IMPORTED_CODE_SVG_BULLETS}

{FORMAT_SVG}"""

IMPORTED_CODE_SYSTEM_PROMPTS = SystemPrompts(
    html_tailwind=IMPORTED_CODE_TAILWIND_SYSTEM_PROMPT,
    html_css=IMPORTED_CODE_HTML_CSS_SYSTEM_PROMPT,
    react_tailwind=IMPORTED_CODE_REACT_TAILWIND_SYSTEM_PROMPT,
    bootstrap=IMPORTED_CODE_BOOTSTRAP_SYSTEM_PROMPT,
    ionic_tailwind=IMPORTED_CODE_IONIC_TAILWIND_SYSTEM_PROMPT,
    vue_tailwind=IMPORTED_CODE_VUE_TAILWIND_SYSTEM_PROMPT,
    svg=IMPORTED_CODE_SVG_SYSTEM_PROMPT,
)
